#!/bin/bash -l

#SBATCH --ntasks=1
#SBATCH -J $f_name
#SBATCH --output=out_files/log_%j.txt
#SBATCH -p cosma8
#SBATCH -A dp004
#SBATCH --exclusive
#SBATCH --cpus-per-task=128
#SBATCH --time=$num_hours_swift:00:00
#SBATCH --no-requeue

module purge
module load intel_comp/2018 intel_mpi/2018 fftw/3.3.7
module load gsl/2.5 hdf5/1.12.0
echo "Loaded swift modules C8 (2018)."

/cosma7/data/dp004/rttw52/swift_runs/swiftsim-flamingo/examples/swift --flamingo --cosmology --pin -v 1 --threads=$$SLURM_CPUS_PER_TASK params.yml

echo "Job done, info follows..."
sacct -j $$SLURM_JOBID --format=JobID,JobName,Partition,AveRSS,MaxRSS,AveVMSize,MaxVMSize,Elapsed,ExitCode
exit
