#!/bin/bash -l

#SBATCH --ntasks=$n_nodes
#SBATCH -J Swift
#SBATCH -o out_files/%x.%J.swift.out
#SBATCH -e out_files/%x.%J.swift.err
#SBATCH -p cosma7-rp
#SBATCH -A dp004
#SBATCH --exclusive
#SBATCH --cpus-per-task=28
#SBATCH --time=$n_hours:00:00

load_swift

mpirun -np $$SLURM_NTASKS --bind-to core --map-by slot:PE=$$SLURM_CPUS_PER_TASK $exec --fof -v 1 --pin --cosmology --self-gravity --threads=$$SLURM_CPUS_PER_TASK params.yml

echo "Job done, info follows..."
sacct -j $$SLURM_JOBID --format=JobID,JobName,Partition,AveRSS,MaxRSS,AveVMSize,MaxVMSize,Elapsed,ExitCode
