#!/bin/bash -l

#SBATCH --ntasks=$n_cores
#SBATCH --job-name=ic_gen
#SBATCH --output=log_%j.txt
#SBATCH --partition=cosma7
#SBATCH --account=dp004
#SBATCH --exclusive
#SBATCH --time=$num_hours:00:00

load_icgen

mpirun -env I_MPI_PIN=1 -env I_MPI_PIN_PROCESSOR_LIST=allcores -np $$SLURM_NTASKS $exec params.inp

echo "Job done, info follows..."
sacct -j $$SLURM_JOBID --format=JobID,JobName,Partition,AveRSS,MaxRSS,AveVMSize,MaxVMSize,Elapsed,ExitCode
exit

